---
- name: Netbox runner
  hosts: netboxrunners
  become: yes
  vars:
    netbox_tools_3_src_dir: /usr/local/netbox-tools-3
    netbox_tools_3_etc_dir: /etc/netbox-tools-3
    netbox_tools_3_out_dir: /data/netbox-tools-3
      # netbox_tools_3_version: main
    netbox_tools_3_version: "0.52"

  pre_tasks:
    - name: include secrets
      ansible.builtin.include_vars:
        file: secrets.yml

  roles:
    - netboxtools
    - netboxrun
    - fetch-netbox-files
