---
- name: Netbox runner
  hosts: netboxrunners
  become: yes

  pre_tasks:
    - name: include secrets
      ansible.builtin.include_vars:
        file: secrets.yml

  roles:
    - fetch-netbox-files
      #- netboxtools
      #- netboxrun
